name: Playwright Tests

on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Get PR commit messages
        id: commits
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMIT_MESSAGES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits" \
                            | jq -r '.[].commit.message' | paste -sd " " -)
          echo "::set-output name=messages::${COMMIT_MESSAGES}"
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests updated snapshots
        if: contains(steps.commits.outputs.messages, '--update-snapshots')
        run: npx playwright test --update-snapshots --reporter=list
      - name: Run tests
        if: ${{ !contains(steps.commits.outputs.messages, '--update-snapshots') }}
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
