name: Conditional Job on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get PR commit messages
        id: commits
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMIT_MESSAGES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits" \
                            | jq -r '.[].commit.message' | paste -sd " " -)
          echo "::set-output name=messages::${COMMIT_MESSAGES}"

      - name: Run conditional step
        if: contains(steps.commits.outputs.messages, '/some-string')
        run: echo "One of the commit messages contains /some-string"
